# By default, attempt to compile using the host compiler toolchain.
# If you have built the cross-compiler, then set this to true instead.
CROSS_COMPILE=false

# This roundabout method finds the directory containing this Makefile.config.
THISFILE_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
THISFILE_DIR := $(dir $(THISFILE_PATH))

ifeq ($(CROSS_COMPILE),true)
    # Select the cross-compilation tools.
    CROSS := $(THISFILE_DIR)/cross
    CC=$(CROSS)/bin/i686-elf-gcc
    LD=$(CROSS)/bin/i686-elf-ld
    KERNEL_LD=$(CROSS)/bin/i686-elf-ld
    AR=$(CROSS)/bin/i686-elf-ar
    OBJCOPY=$(CROSS)/bin/i686-elf-objcopy
else
    # Select the host tools instead.
    CC=gcc -m32
    LD=ld
    KERNEL_LD=ld -melf_i386
    AR=ar
    OBJCOPY=objcopy
endif

# Compiler and linker settings for the kernel proper:
KERNEL_CCFLAGS=-Wall -c -ffreestanding -fno-pie -g -std=gnu99
KERNEL_LDFLAGS=

# Compiler and linker settings for the library and user code:
USER_CCFLAGS=-Wall -c -ffreestanding -fno-pie -g -std=gnu99
USER_LDFLAGS=-z max-page-size=4096 -T basekernel.user.ldscript

# Linux machines typically install genisoimage for cdrom imaging.
ISOGEN=genisoimage
# If building on OSX, then install mkisofs via ports or brew
# and uncomment this:
#ISOGEN=mkisofs

